#!/usr/bin/env bash
#
# Update script for an existing install (see install.sh).
#
# Pulls the latest code with `git pull`, re-syncs build-your-own-game/ into the
# /opt install directory, and restarts the systemd service. NGINX / TLS are left
# untouched (use install.sh for the initial setup or to change the domain/cert).
#
# Usage:
#   sudo ./update.sh
#
set -euo pipefail

# --- locate ourselves -------------------------------------------------------
ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# --- sync checkout with remote (bootstrap) ----------------------------------
# Deployment checkouts should mirror origin exactly. Fetch + hard-reset discards
# accidental local edits to tracked files (including this script). Re-exec after
# reset so the rest of the run uses the freshly checked-out update.sh — otherwise
# bash keeps executing the old in-memory copy and `git pull` can still fail.
if [ -z "${UPDATE_SYNCED:-}" ] && [ -d "${ROOT_DIR}/.git" ] && command -v git >/dev/null 2>&1; then
  git config --global --add safe.directory "$ROOT_DIR" 2>/dev/null || true
  BRANCH="$(git -C "$ROOT_DIR" rev-parse --abbrev-ref HEAD 2>/dev/null || echo main)"
  [ "$BRANCH" != "HEAD" ] || BRANCH="main"
  if git -C "$ROOT_DIR" fetch --prune origin "$BRANCH" 2>/dev/null \
    || git -C "$ROOT_DIR" fetch --prune origin 2>/dev/null; then
    if git -C "$ROOT_DIR" rev-parse --verify "origin/${BRANCH}" >/dev/null 2>&1; then
      if ! git -C "$ROOT_DIR" diff --quiet "origin/${BRANCH}" 2>/dev/null \
        || ! git -C "$ROOT_DIR" diff --quiet || ! git -C "$ROOT_DIR" diff --cached --quiet; then
        printf '\n\033[1;36m==> Syncing checkout to origin/%s (discarding local edits to tracked files)\033[0m\n' "$BRANCH"
      fi
      git -C "$ROOT_DIR" reset --hard "origin/${BRANCH}"
      chmod +x "${ROOT_DIR}/update.sh" "${ROOT_DIR}/install.sh" 2>/dev/null || true
      UPDATE_SYNCED=1 exec bash "$0" "$@"
    fi
  fi
fi

APP_DIR="${ROOT_DIR}/build-your-own-game"
CONFIG_FILE="${ROOT_DIR}/deploy.config"

SERVICE_NAME="build-your-own-game"
INSTALL_DIR="/opt/${SERVICE_NAME}"

log()  { printf '\n\033[1;36m==> %s\033[0m\n' "$*"; }
die()  { printf '\n\033[1;31mERROR: %s\033[0m\n' "$*" >&2; exit 1; }

# --- pre-flight checks ------------------------------------------------------
[ "$(id -u)" -eq 0 ] || die "Please run as root (sudo ./update.sh)."
[ -f "${APP_DIR}/server.mjs" ] || die "Cannot find ${APP_DIR}/server.mjs."
[ -d "${ROOT_DIR}/.git" ] || die "${ROOT_DIR} is not a git checkout; nothing to pull."
command -v git >/dev/null 2>&1 || die "git is not installed."
[ -d "$INSTALL_DIR" ] || die "${INSTALL_DIR} not found. Run sudo ./install.sh first."

# SERVICE_USER comes from deploy.config when present, otherwise default to the
# same dedicated user install.sh creates.
SERVICE_USER="museumapp"
if [ -f "$CONFIG_FILE" ]; then
  # shellcheck disable=SC1090
  source "$CONFIG_FILE"
  SERVICE_USER="${SERVICE_USER:-museumapp}"
fi
id "$SERVICE_USER" >/dev/null 2>&1 || die "Service user '${SERVICE_USER}' does not exist. Run sudo ./install.sh first."

# --- pull latest code (already synced at startup; log revision for clarity) ---
log "Checking out latest code in ${ROOT_DIR}"
git config --global --add safe.directory "$ROOT_DIR" 2>/dev/null || true

BRANCH="$(git -C "$ROOT_DIR" rev-parse --abbrev-ref HEAD 2>/dev/null || echo main)"
[ "$BRANCH" != "HEAD" ] || BRANCH="main"
BEFORE="$(git -C "$ROOT_DIR" rev-parse HEAD 2>/dev/null || echo none)"

git -C "$ROOT_DIR" fetch --prune origin "$BRANCH" 2>/dev/null \
  || git -C "$ROOT_DIR" fetch --prune origin
git -C "$ROOT_DIR" reset --hard "origin/${BRANCH}"

AFTER="$(git -C "$ROOT_DIR" rev-parse HEAD 2>/dev/null || echo none)"
if [ "$BEFORE" = "$AFTER" ]; then
  log "Already up to date (${AFTER}). Re-syncing and restarting anyway."
else
  log "Updated ${BEFORE} -> ${AFTER}"
fi

# --- re-sync the app into /opt ----------------------------------------------
log "Syncing app into ${INSTALL_DIR}"
command -v rsync >/dev/null 2>&1 || { apt-get update -y && apt-get install -y rsync; }
rsync -a --delete \
  --exclude ".git" \
  --exclude "node_modules" \
  "${APP_DIR}/" "${INSTALL_DIR}/"

# Re-apply runtime config from deploy.config (rsync would overwrite it).
if [ -f "$CONFIG_FILE" ]; then
  # shellcheck disable=SC1090
  source "$CONFIG_FILE"
  DOMAIN="${DOMAIN:-example.com}"
  QR_BASE_URL="${QR_BASE_URL:-https://${DOMAIN}/}"
  case "$QR_BASE_URL" in
    */) ;;
    *) QR_BASE_URL="${QR_BASE_URL}/" ;;
  esac
  log "Writing runtime config (QR base URL: ${QR_BASE_URL})"
  cat > "${INSTALL_DIR}/config.js" <<EOF
// Generated by update.sh from deploy.config — do not edit by hand.
window.QR_BASE_URL = "${QR_BASE_URL}";
EOF
fi

chown -R "$SERVICE_USER":"$SERVICE_USER" "$INSTALL_DIR"

# --- restart the service ----------------------------------------------------
log "Restarting service: ${SERVICE_NAME}"
systemctl restart "$SERVICE_NAME"
sleep 2
systemctl is-active --quiet "$SERVICE_NAME" \
  || die "Service ${SERVICE_NAME} failed to start. Check: journalctl -u ${SERVICE_NAME} -n 50"

log "Done!"
echo "  App dir : ${INSTALL_DIR}  (synced from ${APP_DIR})"
echo "  Service : systemctl status ${SERVICE_NAME}"
echo "  Logs    : journalctl -u ${SERVICE_NAME} -f"
