/*
 * Runtime configuration for the kiosk front-end.
 *
 * On a deployed server this file is regenerated by install.sh from the values
 * in deploy.config. The value here is only the local/dev default.
 *
 * QR_BASE_URL: base URL encoded into the share QR code shown on the results
 * screen (the visitor scans it to replay their game on their phone).
 */
window.QR_BASE_URL = "https://example.com/";
